algoritmo "kreusa quer comprar dolares"
var
    Reais,dolar:real
    
    Procedimento Conversor(A, B: real)
    Var z: real
    Inicio
    z<-reais/dolar
    Escreval("com essa quantidade de reais voce consegue comprar ", z:4:2," dolares")
    FimProcedimento
    
inicio
    Escreval("quanto voce tem em reais?")
    Leia(reais)
    Escreval("qual a cotação do dolar hoje?")
    Leia(dolar)
    Conversor(reais, dolar)
fimalgoritmo