algoritmo "SomaParametrosReferencia"
var
   x,y:inteiro
   procedimento soma(var a,b:inteiro)
   inicio
          a<-a+1
          b<-b+2
          Escreval("valor de a = ", a)
          Escreval("valor de b = ", b)
          Escreval("soma de a + b = ", a+b)
   FimProcedimento
inicio
      x<-4
      y<-8
      soma(X,Y)
      Escreval("o valor de x = ", x)
      Escreval("o valor de y = ", y)
fimalgoritmo