algoritmo "SomadeValores"
var

Procedimento soma(A,B: inteiro)
Var
   s: inteiro
Inicio
   s<- A + B
   Escreval("A soma entre ", N1," e",N2," e igual a ",s)
FimProcedimento

  N1, N2: inteiro

inicio
  Escreva("informe um numero: ")
  Leia(N1)
  Escreva("informe outro numero: ")
  Leia(N2)
  soma(n1,n2)
  Escreval("O Numero digitado foi: ", N1)
  Escreval("O Numero digitado foi: ", N2)
fimalgoritmo